services:
  express_app:
    image: mustakquimdiwan/express_app
    container_name: express_app
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - MYSQL_HOST=mysql_container
    env_file:
      - .env
    depends_on:
      mysql_container:
        condition: service_healthy

  mysql_container:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysql_db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_db:

networks:
  mynetwork:
